using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UIElements;
using Unity.AppUI.Navigation;
using Unity.AppUI.UI;

/// <summary>
/// Complete example showing how to set up a navigation system with App UI.
/// This example creates a multi-screen app with bottom navigation and demonstrates:
/// - NavGraph and NavDestination creation
/// - NavAction definitions with different back stack behaviors
/// - NavHost setup with a custom visual controller
/// - INavVisualController implementation
/// - NavigationScreen subclasses
/// - Navigation between screens with proper visual component setup
/// </summary>

#region Constants (Generated by Navigation Graph Editor)

public partial static class Actions
{
    public const string NavigateToHome = "navigateToHome";
    public const string NavigateToExplore = "navigateToExplore";
    public const string NavigateToSaved = "navigateToSaved";
    public const string NavigateToProfile = "navigateToProfile";
    public const string ViewDetails = "viewDetails";
    public const string Logout = "logout";
}

public partial class Destinations
{
    public const string Home = "home";
    public const string Explore = "explore";
    public const string Saved = "saved";
    public const string Profile = "profile";
    public const string Details = "details";
    public const string Login = "login";
}

#endregion

#region Navigation Screens

/// <summary>
/// Base navigation screen with standard setup.
/// This demonstrates how to override SetupAppBar and SetupBottomNavBar
/// for per-screen customization in addition to the global visual controller.
/// </summary>
public class HomeScreen : NavigationScreen
{
    private Label m_ContentLabel;

    public override void OnEnter(NavController controller, NavDestination destination, Argument[] args)
    {
        base.OnEnter(controller, destination, args);

        // Create content for this screen
        m_ContentLabel = new Label("Welcome to Home Screen");
        m_ContentLabel.style.fontSize = 24;
        m_ContentLabel.style.marginTop = 20;
        m_ContentLabel.style.marginBottom = 20;
        Add(m_ContentLabel);

        // Add a button to navigate to details
        var detailsButton = new Button(() => controller.Navigate(Actions.ViewDetails, new[]
        {
            new Argument { key = "itemId", value = "home-item-1" },
            new Argument { key = "itemName", value = "Home Item" }
        }))
        {
            text = "View Details"
        };
        detailsButton.style.marginTop = 10;
        Add(detailsButton);
    }

    protected override void SetupAppBar(AppBar appBar, NavController navController)
    {
        base.SetupAppBar(appBar, navController);
        appBar.title = "Home";

        // Add custom action button for home screen
        var refreshButton = new ActionButton { icon = "refresh", label = "Refresh" };
        refreshButton.clickable.clicked += () => Debug.Log("Refresh clicked");
        appBar.Add(refreshButton);
    }

    public override void OnExit(NavController controller, NavDestination destination, Argument[] args)
    {
        base.OnExit(controller, destination, args);
        // Cleanup code if needed
    }
}

/// <summary>
/// Explore screen demonstrating navigation with arguments.
/// </summary>
public class ExploreScreen : NavigationScreen
{
    public override void OnEnter(NavController controller, NavDestination destination, Argument[] args)
    {
        base.OnEnter(controller, destination, args);

        var content = new Label("Explore content goes here");
        content.style.marginTop = 20;
        Add(content);

        var navigateButton = new Button(() => controller.Navigate(Actions.ViewDetails, new[]
        {
            new Argument { key = "itemId", value = "explore-item-1" },
            new Argument { key = "itemName", value = "Explore Item" }
        }))
        {
            text = "Show Details"
        };
        Add(navigateButton);
    }

    protected override void SetupAppBar(AppBar appBar, NavController navController)
    {
        base.SetupAppBar(appBar, navController);
        appBar.title = "Explore";
    }
}

/// <summary>
/// Saved items screen.
/// </summary>
public class SavedScreen : NavigationScreen
{
    public override void OnEnter(NavController controller, NavDestination destination, Argument[] args)
    {
        base.OnEnter(controller, destination, args);

        var content = new Label("Your saved items appear here");
        content.style.marginTop = 20;
        Add(content);
    }

    protected override void SetupAppBar(AppBar appBar, NavController navController)
    {
        base.SetupAppBar(appBar, navController);
        appBar.title = "Saved";
    }
}

/// <summary>
/// User profile screen.
/// </summary>
public class ProfileScreen : NavigationScreen
{
    public override void OnEnter(NavController controller, NavDestination destination, Argument[] args)
    {
        base.OnEnter(controller, destination, args);

        var content = new Label("Your profile information");
        content.style.marginTop = 20;
        Add(content);

        var logoutButton = new Button(() => controller.Navigate(Actions.Logout))
        {
            text = "Logout"
        };
        Add(logoutButton);
    }

    protected override void SetupAppBar(AppBar appBar, NavController navController)
    {
        base.SetupAppBar(appBar, navController);
        appBar.title = "Profile";

        var settingsButton = new ActionButton { icon = "settings", label = "Settings" };
        appBar.Add(settingsButton);
    }
}

/// <summary>
/// Details screen that receives arguments from navigation.
/// Demonstrates how to extract and use arguments from the navigation call.
/// </summary>
public class DetailsScreen : NavigationScreen
{
    private Label m_TitleLabel;
    private Label m_IdLabel;

    public override void OnEnter(NavController controller, NavDestination destination, Argument[] args)
    {
        base.OnEnter(controller, destination, args);

        // Extract arguments from navigation
        string itemId = "unknown";
        string itemName = "Unknown Item";

        foreach (var arg in args)
        {
            if (arg.key == "itemId")
                itemId = arg.value.ToString();
            else if (arg.key == "itemName")
                itemName = arg.value.ToString();
        }

        // Display the details
        m_TitleLabel = new Label($"Item: {itemName}");
        m_TitleLabel.style.fontSize = 20;
        m_TitleLabel.style.marginTop = 20;
        Add(m_TitleLabel);

        m_IdLabel = new Label($"ID: {itemId}");
        m_IdLabel.style.marginTop = 10;
        Add(m_IdLabel);

        // Back button
        var backButton = new Button(() =>
        {
            if (controller.canNavigateBack)
                controller.NavigateBack();
        })
        {
            text = "Go Back"
        };
        backButton.style.marginTop = 20;
        Add(backButton);
    }

    protected override void SetupAppBar(AppBar appBar, NavController navController)
    {
        base.SetupAppBar(appBar, navController);
        appBar.title = "Details";
        // AppBar will show back button automatically due to back stack
    }
}

/// <summary>
/// Login screen for authentication flow.
/// </summary>
public class LoginScreen : NavigationScreen
{
    public override void OnEnter(NavController controller, NavDestination destination, Argument[] args)
    {
        base.OnEnter(controller, destination, args);

        var titleLabel = new Label("Login");
        titleLabel.style.fontSize = 24;
        titleLabel.style.marginTop = 20;
        Add(titleLabel);

        var usernameField = new TextField("Username");
        usernameField.style.marginTop = 20;
        Add(usernameField);

        var passwordField = new TextField("Password");
        passwordField.isPasswordField = true;
        passwordField.style.marginTop = 10;
        Add(passwordField);

        var loginButton = new Button(() =>
        {
            // After login, navigate to home with ClearStack behavior
            controller.Navigate(Actions.NavigateToHome);
        })
        {
            text = "Login"
        };
        loginButton.style.marginTop = 20;
        Add(loginButton);
    }

    protected override void SetupAppBar(AppBar appBar, NavController navController)
    {
        base.SetupAppBar(appBar, navController);
        appBar.title = "Login";
    }
}

#endregion

#region Visual Controller

/// <summary>
/// Custom navigation visual controller that manages AppBar, Drawer, BottomNavBar, and NavigationRail.
/// This example demonstrates a bottom navigation pattern suitable for mobile-like UIs.
/// </summary>
public class AppNavVisualController : INavVisualController
{
    public void SetupAppBar(AppBar appBar, NavDestination destination, NavController navController)
    {
        // The AppBar title is commonly set based on the destination
        appBar.title = destination.label;
        appBar.showMenuButton = false; // No drawer in this example
    }

    public void SetupDrawer(Drawer drawer, NavDestination destination, NavController navController)
    {
        // In this example, we use BottomNavBar instead of Drawer
        // But if you need a drawer, implement it here
        drawer.Add(new DrawerHeader { title = "Navigation" });
        drawer.Add(new Divider { vertical = false });

        var homeItem = new MenuItem { icon = "home", label = "Home", selectable = true };
        homeItem.SetValueWithoutNotify(destination.name == Destinations.Home);
        homeItem.clickable.clicked += () => navController.Navigate(Actions.NavigateToHome);
        drawer.Add(homeItem);
    }

    public void SetupBottomNavBar(BottomNavBar bottomNavBar, NavDestination destination, NavController navController)
    {
        // Home navigation item
        var homeItem = new BottomNavBarItem("home", "Home", () => navController.Navigate(Actions.NavigateToHome))
        {
            isSelected = destination.name == Destinations.Home
        };
        bottomNavBar.Add(homeItem);

        // Explore navigation item
        var exploreItem = new BottomNavBarItem("explore", "Explore", () => navController.Navigate(Actions.NavigateToExplore))
        {
            isSelected = destination.name == Destinations.Explore
        };
        bottomNavBar.Add(exploreItem);

        // Saved navigation item
        var savedItem = new BottomNavBarItem("bookmark", "Saved", () => navController.Navigate(Actions.NavigateToSaved))
        {
            isSelected = destination.name == Destinations.Saved
        };
        bottomNavBar.Add(savedItem);

        // Profile navigation item
        var profileItem = new BottomNavBarItem("person", "Profile", () => navController.Navigate(Actions.NavigateToProfile))
        {
            isSelected = destination.name == Destinations.Profile
        };
        bottomNavBar.Add(profileItem);
    }

    public void SetupNavigationRail(NavigationRail navigationRail, NavDestination destination, NavController navController)
    {
        navigationRail.anchor = NavigationRailAnchor.Start;
        navigationRail.labelType = LabelType.Selected;

        var homeItem = new NavigationRailItem { icon = "home", label = "Home", selected = destination.name == Destinations.Home };
        homeItem.clickable.clicked += () => navController.Navigate(Actions.NavigateToHome);
        navigationRail.mainContainer.Add(homeItem);

        var exploreItem = new NavigationRailItem { icon = "explore", label = "Explore", selected = destination.name == Destinations.Explore };
        exploreItem.clickable.clicked += () => navController.Navigate(Actions.NavigateToExplore);
        navigationRail.mainContainer.Add(exploreItem);
    }
}

#endregion

#region Navigation Graph Setup

/// <summary>
/// Factory for creating the navigation graph at runtime.
/// This demonstrates programmatic graph construction.
/// In practice, you would typically create graphs in the Navigation Graph Editor
/// and load them as assets.
/// </summary>
public static class NavigationGraphFactory
{
    public static NavGraphViewAsset CreateNavigationGraph()
    {
        // Create the main graph
        var mainGraph = new NavGraph { name = "main" };

        // Create destinations
        var homeDestination = CreateDestination(
            Destinations.Home,
            "Home",
            typeof(HomeScreen),
            showAppBar: true,
            showBottomNavBar: true
        );

        var exploreDestination = CreateDestination(
            Destinations.Explore,
            "Explore",
            typeof(ExploreScreen),
            showAppBar: true,
            showBottomNavBar: true
        );

        var savedDestination = CreateDestination(
            Destinations.Saved,
            "Saved",
            typeof(SavedScreen),
            showAppBar: true,
            showBottomNavBar: true
        );

        var profileDestination = CreateDestination(
            Destinations.Profile,
            "Profile",
            typeof(ProfileScreen),
            showAppBar: true,
            showBottomNavBar: true
        );

        var detailsDestination = CreateDestination(
            Destinations.Details,
            "Details",
            typeof(DetailsScreen),
            showAppBar: true,
            showBottomNavBar: false
        );

        var loginDestination = CreateDestination(
            Destinations.Login,
            "Login",
            typeof(LoginScreen),
            showAppBar: true,
            showBottomNavBar: false
        );

        // Add destinations to graph
        mainGraph.destinations.Add(homeDestination);
        mainGraph.destinations.Add(exploreDestination);
        mainGraph.destinations.Add(savedDestination);
        mainGraph.destinations.Add(profileDestination);
        mainGraph.destinations.Add(detailsDestination);
        mainGraph.destinations.Add(loginDestination);

        // Set home as start destination
        mainGraph.startDestination = homeDestination;

        // Create navigation actions
        var navigateToHomeAction = new NavAction
        {
            actionId = Actions.NavigateToHome,
            destination = homeDestination,
            backStackBehavior = BackStackBehavior.PopUntilInclusive
        };
        mainGraph.globalActions.Add(navigateToHomeAction);

        var navigateToExploreAction = new NavAction
        {
            actionId = Actions.NavigateToExplore,
            destination = exploreDestination,
            backStackBehavior = BackStackBehavior.PopUntilInclusive
        };
        mainGraph.globalActions.Add(navigateToExploreAction);

        var navigateToSavedAction = new NavAction
        {
            actionId = Actions.NavigateToSaved,
            destination = savedDestination,
            backStackBehavior = BackStackBehavior.PopUntilInclusive
        };
        mainGraph.globalActions.Add(navigateToSavedAction);

        var navigateToProfileAction = new NavAction
        {
            actionId = Actions.NavigateToProfile,
            destination = profileDestination,
            backStackBehavior = BackStackBehavior.PopUntilInclusive
        };
        mainGraph.globalActions.Add(navigateToProfileAction);

        var viewDetailsAction = new NavAction
        {
            actionId = Actions.ViewDetails,
            destination = detailsDestination,
            backStackBehavior = BackStackBehavior.Push
        };
        mainGraph.globalActions.Add(viewDetailsAction);

        var logoutAction = new NavAction
        {
            actionId = Actions.Logout,
            destination = loginDestination,
            backStackBehavior = BackStackBehavior.ClearStack
        };
        mainGraph.globalActions.Add(logoutAction);

        // Create the asset
        var graphViewAsset = ScriptableObject.CreateInstance<NavGraphViewAsset>();
        graphViewAsset.graphs.Add(mainGraph);

        return graphViewAsset;
    }

    private static NavDestination CreateDestination(
        string name,
        string label,
        Type screenType,
        bool showAppBar = true,
        bool showBottomNavBar = false
    )
    {
        return new NavDestination
        {
            name = name,
            label = label,
            template = new DefaultDestinationTemplate
            {
                screenType = screenType,
                showAppBar = showAppBar,
                showBottomNavBar = showBottomNavBar,
                showDrawer = false,
                showNavigationRail = false
            }
        };
    }
}

#endregion

#region Application Setup

/// <summary>
/// Example MonoBehaviour that sets up the navigation system.
/// This demonstrates how to initialize NavHost with a navigation graph
/// and connect it to your UI.
/// </summary>
public class NavigationAppSetup : MonoBehaviour
{
    private NavHost m_NavHost;
    private NavGraphViewAsset m_NavigationGraph;

    private void OnEnable()
    {
        SetupNavigation();
    }

    private void SetupNavigation()
    {
        // Get the root UI element (usually from UIDocument)
        var rootElement = GetComponent<UIDocument>()?.rootVisualElement;
        if (rootElement == null)
        {
            Debug.LogError("UIDocument not found");
            return;
        }

        // Create or load the navigation graph
        // In production, you would typically load this as an asset:
        // m_NavigationGraph = Resources.Load<NavGraphViewAsset>("Navigation/MainGraph");
        m_NavigationGraph = NavigationGraphFactory.CreateNavigationGraph();

        // Create the NavHost
        m_NavHost = new NavHost();

        // Set the visual controller
        m_NavHost.visualController = new AppNavVisualController();

        // Load the navigation graph
        m_NavHost.LoadGraph(m_NavigationGraph);

        // Subscribe to navigation events
        m_NavHost.onNavigate += OnNavigate;
        m_NavHost.onDestinationEnter += OnDestinationEnter;
        m_NavHost.onDestinationExit += OnDestinationExit;

        // Add to UI
        rootElement.Add(m_NavHost);
    }

    private void OnNavigate(NavController controller, NavDestination destination)
    {
        Debug.Log($"Navigated to: {destination.label}");
    }

    private void OnDestinationEnter(NavController controller, NavDestination destination)
    {
        Debug.Log($"Entered destination: {destination.label}");
    }

    private void OnDestinationExit(NavController controller, NavDestination destination)
    {
        Debug.Log($"Exited destination: {destination.label}");
    }
}

#endregion
